name: CI

on: push
jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build gym_chess docker image
      run: docker build ./Gym_Chess/. -t stockfish-image
